### PR TITLE
Fix typos.

### PR DESCRIPTION
**Pull request by kayakr**

### CODE REVIEW

**Comment by willtp87** [comment]
@kayakr These fixes look good, thanks for the work. I think this is your first pull. Are you covered by a CLA as in the [contributing](https://github.com/Islandora/tuque/blob/1.x/CONTRIBUTING.md) file?
@manez May be able to help you if not.

**Comment by kayakr** [comment]
@willtp87 CLA sent to community@islandora.ca

**Comment by manez** [comment]
Got the CLA. Public list not updated yet, but this is good to go.

**Review by willtp87 — APPROVED** [review]

**Comment by DiegoPino** [comment]
Thanks @kayakr for this contribution!

**Pull request merged**
