### PR TITLE
Loss of potential RELS-INT statements when the RELS-INT does not exist

### PR DESCRIPTION
**Pull request by jordandukart**
Release pull for https://github.com/Islandora/tuque/pull/161

### CODE REVIEW

**Comment by DiegoPino** [comment]
@jordandukart great! Merging now ~~and marking ISLANDORA-2067 as done.~~ Keeping open until XACML editor one gets merged

**Comment by jordandukart** [comment]
@DiegoPino there's an open XACML editor ticket to identify and fix issues.

**Comment by DiegoPino** [comment]
@jordandukart saw it. Did you finish addressing @adam-vessey concerns? Want a second pair of eyes?

**Comment by jordandukart** [comment]
I mean in terms of closing ISLANDORA-2067.

**Comment by DiegoPino** [comment]
@jordandukart will keep  ISLANDORA-2067 open until https://github.com/Islandora/islandora_xacml_editor/pull/138 goes through. Also moved ISLANDORA-2067 to "BUG"

**Pull request merged**
