### PR TITLE
Moving from inline to managed datastreams to ease 409s from Fedora.

### PR DESCRIPTION
**Pull request by willtp87**

### CODE REVIEW

**Comment by willtp87** [comment]
https://jira.duraspace.org/browse/ISLANDORA-1475

**Comment by DiegoPino** [comment]
Makes sense for having "slimmer" FOXML :+1:

**Comment by willtp87** [comment]
https://jira.duraspace.org/browse/FCREPO-849 I'll not get back to this until Tuesday, have a solution.

**Comment by willtp87** [comment]
I'll re-open when this isn't a very dangerous merge.

**Comment by DiegoPino** [comment]
Will, this is an issue only if "versionable" is off, should not be a problem for us in RELS-EXT?. And we won't get fixes for fcp3

**Pull request closed without merging**
