### PR TITLE
Export objects to files

### PR DESCRIPTION
**Pull request by adam-vessey**
**JIRA Ticket**: [ISLANDORA-1893](https://jira.duraspace.org/browse/ISLANDORA-1893)

# What does this Pull Request do?

Allow Tuque to write object exports from Fedora directly to files. Presently, Tuque fetches exports into memory, which can result in extremely high memory usage should objects contain large datastreams. 

# What's new?

Add an additional parameter to the [`FedoraApiM::export()`](https://github.com/Islandora/tuque/blob/e2d22fc124f929ed57490288035a1f96e294fd4b/FedoraApi.php#L763-L798) and [`FedoraApiM::getObjectXML()`](https://github.com/Islandora/tuque/blob/e2d22fc124f929ed57490288035a1f96e294fd4b/FedoraApi.php#L962-L982) methods, handled in much the same manner as [`FedoraApiA::getDatastreamDissemination()`](https://github.com/Islandora/tuque/blob/e2d22fc124f929ed57490288035a1f96e294fd4b/FedoraApi.php#L315-L347)'s [`$file` parameter](https://github.com/Islandora/tuque/blob/e2d22fc124f929ed57490288035a1f96e294fd4b/FedoraApi.php#L326-L327). 

# How should this be tested?
There are no invocations of `FedoraApiM::export()` or `FedoraApiM::getObjectXML()` in the core of Islandora... As such, could just roll something like:

```php
<?php
$tuque = islandora_get_tuque_connection();
$temp_file = drupal_tempnam('temporary://', 'temp');
$tuque->api->m->export('islandora:root', array(), $temp_file);
print(file_get_contents($temp_file) === $tuque->api->m->export('islandora:root') ? 'equal' : 'different');
```

... Which is to say, the content of the file is the exact same as the string which was previously returned from the `FedoraApiM::export()` call (and similarly for `FedoraApiM::getObjectXML()`). 

# Additional Notes:

* Does this change require documentation to be updated? No. 
* Does this change add any new dependencies? No.
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? No.
* Could this change impact execution of existing code? No.

# Interested parties

Tagging @DiegoPino and @willtp87 as maintainers.

### CODE REVIEW

**Comment by DiegoPino** [comment]
@adam-vessey very interesting! I already have some use cases scenarios (probably the same that inspired this pull). Will review this weekend. Best!

**Review by DiegoPino — COMMENTED** [review]
The code does not affect running/existing implementations. I wonder what happens if $file, assuming it's a string with a path, is not accessible? Will that fail twice, on getRequest and getObjectXml? and how badly?

**Comment by adam-vessey** [comment]
@DiegoPino If the path isn't _writable_, then I would expect the download to fail inside of the `HttpConnection::getRequest()` call, in much the same manner as `Datastream::getContent()` would presently... Easy enough to see how it fails...:

... The `Datastream::getContent()`, on which the code here is based:
```php
$tuque = islandora_get_tuque_connection();
$temp_file = '/cannot/write/here';
$object = islandora_object_load('islandora:root');
$object['DC']->getContent($temp_file);
```
yielding:
Screenshot the first

Similarly, `FedoraApiM::export()`:
```php
$tuque = islandora_get_tuque_connection();
$temp_file = '/cannot/write/here_either';
$tuque->api->m->export('islandora:root', array(), $temp_file);
```
yielding:
Screenshot the second

And `FedoraApiM::getObjectXml()`:
```php
$tuque = islandora_get_tuque_connection();
$temp_file = '/cannot/write/things';
$tuque->api->m->getObjectXML('islandora:root', $temp_file);
```
yielding:
Screenshot the third

Looking at the response, it appears that this would continue to submit the request as if `$file` were not passed... As in, in `FedoraApiMSerializer::getObjectXml()`, looking at the value of `$request`:
```
Array
(
    [status] => 200
    [headers] => <?xml version="1.0" encoding="UTF-8"?>
<foxml:digitalObject VERSION="1.1" PID="islandora:root"
xmlns:foxml="info:fedora/fedora-system:def/foxml#"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schema
    [content] => ocation="info:fedora/fedora-system:def/foxml# http://www.fedora.info/definitions/1/0/foxml1-1.xsd">
<foxml:objectProperties>
<foxml:property NAME="info:fedora/fedora-system:def/model#state" VALUE="Active"/>
<foxml:property NAME="info:fedora/fedora-system:def/model#label" VALUE="Top-level Collection"/>
<foxml:property NAME="info:fedora/fedora-system:def/model#ownerId" VALUE="fedoraAdmin"/>
<foxml:property NAME="info:fedora/fedora-system:def/model#createdDate" VALUE="2017-01-20T15:52:20.104Z"/>
<foxml:property NAME="info:fedora/fedora-system:def/view#lastModifiedDate" VALUE="2017-01-20T15:52:20.104Z"/>
</foxml:objectProperties>
<foxml:datastream ID="RELS-EXT" STATE="A" CONTROL_GROUP="X" VERSIONABLE="true">
<foxml:datastreamVersion ID="RELS-EXT.0" LABEL="Fedora Object to Object Relationship Metadata." CREATED="2017-01-20T15:52:20.104Z" MIMETYPE="application/rdf+xml" FORMAT_URI="info:fedora/fedora-system:FedoraRELSExt-1.0" SIZE="443">
<foxml:xmlContent>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:fedora="info:fedora/fedora-system:def/relations-external#" xmlns:fedora-model="info:fedora/fedora-system:def/model#" xmlns:islandora="http://islandora.ca/ontology/relsext#">
  <rdf:Description rdf:about="info:fedora/islandora:root">
    <fedora-model:hasModel rdf:resource="info:fedora/islandora:collectionCModel"></fedora-model:hasModel>
  </rdf:Description>
</rdf:RDF>
</foxml:xmlContent>
</foxml:datastreamVersion>
</foxml:datastream>
<foxml:datastream ID="COLLECTION_POLICY" STATE="A" CONTROL_GROUP="M" VERSIONABLE="true">
<foxml:datastreamVersion ID="COLLECTION_POLICY.0" LABEL="Collection policy" CREATED="2017-01-20T15:52:20.104Z" MIMETYPE="application/xml" SIZE="1209">
<foxml:contentLocation TYPE="INTERNAL_ID" REF="islandora:root+COLLECTION_POLICY+COLLECTION_POLICY.0"/>
</foxml:datastreamVersion>
</foxml:datastream>
<foxml:datastream ID="TN" STATE="A" CONTROL_GROUP="M" VERSIONABLE="true">
<foxml:datastreamVersion ID="TN.0" LABEL="Thumbnail" CREATED="2017-01-20T15:52:20.104Z" MIMETYPE="image/png" SIZE="5137">
<foxml:contentLocation TYPE="INTERNAL_ID" REF="islandora:root+TN+TN.0"/>
</foxml:datastreamVersion>
</foxml:datastream>
<foxml:datastream ID="DC" STATE="A" CONTROL_GROUP="X" VERSIONABLE="true">
<foxml:datastreamVersion ID="DC1.0" LABEL="Dublin Core Record for this object" CREATED="2017-01-20T15:52:20.104Z" MIMETYPE="text/xml" FORMAT_URI="http://www.openarchives.org/OAI/2.0/oai_dc/" SIZE="387">
<foxml:xmlContent>
<oai_dc:dc xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd">
  <dc:title>Top-level Collection</dc:title>
  <dc:identifier>islandora:root</dc:identifier>
</oai_dc:dc>
</foxml:xmlContent>
</foxml:datastreamVersion>
</foxml:datastream>
</foxml:digitalObject>
)
```

So it would be possible to blow up due to memory; though, how far to go? Really, passing an unwritable file as a file to which to write would seem to fall under the whole "garbage in, garbage out" idea... We _could_ check that the file was able to be opened correctly inside `HttpConnection::getRequest()`; however, this is getting somewhat outside of the scope of this...

**Review by DiegoPino — APPROVED** [review]
@adam-vessey true. The passing of invalid values to the function ($file, string) is out of the scope probably of this pull, but if possible, maybe we could avoid a bit of burden of that by adding a more explicit doc comment to the variable definition of $file. Documentation should be good enough in that case. I approve this. Will wait for your answer on this, because maybe you have a better idea.

**Comment by adam-vessey** [comment]
@DiegoPino Any suggested phrasing? Anything I'm thinking of feels a little too redundant... It's somewhere to download, so it has to be writable, yeah?

**Comment by DiegoPino** [comment]
@adam-vessey sorry, I'm so redundant in my writing. Maybe just stating that the string is a file's full path? Not sure, but I do trust you will come with the perfect wording. If it gets too complicated we can always just merge. Don't think this functions will be used by a lot of users.

**Comment by adam-vessey** [comment]
@DiegoPino Updated the doc comments on the parameters. Also, I've spawned https://jira.duraspace.org/browse/ISLANDORA-1894 to address the behaviour when passed something that is not a writable file path.

**Comment by DiegoPino** [comment]
@adam-vessey cool. Will merge once Travis passes. Thanks!

**Comment by adam-vessey** [comment]
Thanks, @DiegoPino!

**Pull request merged**
