### PR TITLE
FedoraRelationships::getXpathResults can now have a predicate without a predicate URI

### PR DESCRIPTION
**Pull request by ncphillips**

### CODE REVIEW

**Comment by willtp87** [comment]
What's your goal here?

**Comment by willtp87** [comment]
The fix looks good, the feature itself is dangerous though and I would like to advise against it's use.  This can be merged once Travis starts cooperating but I'm going to pop a ticket to deprecate or minimaly document this dangerous behavior.

**Comment by ncphillips** [comment]
In FedoraRelationship::get($pred_uri, $pred, $object), and other such functions, it's documented  that: 

"Any parameter [...] can be set to NULL to act as a wildcard."

It was true for `get(null, null)` and `get($pred_uri, null)` but not for `get(null, $pred)`.

My change corrects this bug so you can look for a relationship called $pred from any namespace.

**Comment by ncphillips** [comment]
It's being used in a situation where the requested relationship $pred is being taken from a Solr search field, which does not include the NS.

**Comment by willtp87** [comment]
I've popped https://jira.duraspace.org/browse/ISLANDORA-1001 to address my concerns.  For your use case I would suggest getting the entire predicate from a different source:
- declaring it in code
- declaring it in configuration
- indexing the full predicate

**Pull request merged**
