### PR TITLE
1.x

### PR DESCRIPTION
**Pull request by acoburn**
In certain cases, a given user may not have direct access to the RELS-EXT datastream. If that is the case, calls to $obj->models (i.e. get or isset) will throw an exception. The data, however, can just as easily be fetched from the resource index.

### CODE REVIEW

**Comment by jonathangreen** [comment]
Hey Aaron. Can you maybe turn this into a configuration option and clean up the commit log? I agree there may be instances where the user doesn't have access to the RELS-\* datasteam, however there is also a install time option to disable the resource index (and its disabled by default), so I don't want to make Tuque depend on the RI being enabled.

**Comment by acoburn** [comment]
By configuration option, what would you think of adding a flag to the FedoraRepository constructor (and a corresponding property)? i.e.

__construct(FedoraApi $api, AbstractCache $cache, $useResourceIndex=False)

Then, when the $obj->models getter is accessed, it will use the RI if the $repository->useResourceIndex property is True, but will access RELS-EXT directly if not. This also keeps RI use disabled by default.

Any yes, I'll clean up the history -- I'm still a bit of a git n00b, but I'm becoming more familiar with the rebase command.

**Comment by jonathangreen** [comment]
Sounds like a good plan to me.

**Comment by acoburn** [comment]
This request has been moved to https://github.com/Islandora/tuque/pull/39

**Pull request closed without merging**
